export {default as earth} from '../../maps/mpl/gist_earth.js'
export {default as gray} from '../../maps/mpl/gist_gray.js'
export {default as heat} from '../../maps/mpl/gist_heat.js'
export {default as ncar} from '../../maps/mpl/gist_ncar.js'
export {default as rainbow} from '../../maps/mpl/gist_rainbow.js'
export {default as stern} from '../../maps/mpl/gist_stern.js'
export {default as yarg} from '../../maps/mpl/gist_yarg.js'
