export * from './index-imp.js'

export {default as afmhot} from './afmhot.js'
export {default as cubehelix} from './cubehelix.js'
export {default as flag} from './flag.js'
export {default as gist_heat} from './gist_heat.js'
export {default as gist_gray} from './gist_gray.js'
export {default as gist_yarg} from './gist_yarg.js'
export {default as gnuplot} from './gnuplot.js'
export {default as gnuplot2} from './gnuplot2.js'
export {default as ocean} from './ocean.js'
export {default as prism} from './prism.js'
export {default as rainbow} from './rainbow.js'
export {default as twilight_shifted} from './twilight_shifted.js'
