export {default as blue_green} from './blue-green.js'
export {default as blue_red} from './blue-red.js'
export {default as green_blue} from './green-blue.js'
export {default as green_red} from './green-red.js'
export {default as red_blue} from './red-blue.js'
export {default as red_green} from './red-green.js'
