export {default as blue_green} from '../../maps/other/blue-green.js'
export {default as blue_red} from '../../maps/other/blue-red.js'
export {default as green_blue} from '../../maps/other/green-blue.js'
export {default as green_red} from '../../maps/other/green-red.js'
export {default as red_blue} from '../../maps/other/red-blue.js'
export {default as red_green} from '../../maps/other/red-green.js'
